default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['PSQL_USERNAME'] %>
  password: <%= ENV['PSQL_PASSWORD'] %>
  host: <%= ENV['PGHOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_test_development

test:
  <<: *default
  database: api_test_test

production:
  <<: *default
  database: api_test_production
